export const SUCCESS_GET_LIST_CONTACT = 'SUCCESS_GET_LIST_CONTACT';
export const LOADING_GET_LIST_CONTACT = 'PANDING_GET_LIST_CONTACT';
export const ERROR_GET_LIST_CONTACT = 'ERROR_GET_LIST_CONTACT';

export const SUCCESS_GET_DETAIL_CONTACT = 'SUCCESS_GET_DETAIL_CONTACT';
export const LOADING_GET_DETAIL_CONTACT = 'PANDING_GET_DETAIL_CONTACT';
export const ERROR_GET_DETAIL_CONTACT = 'ERROR_GET_DETAIL_CONTACT';
export const RESET_GET_DETAIL_CONTACT = 'RESET_GET_DETAIL_CONTACT';

export const LOADING_ADD_CONTACT = 'LOADING_ADD_CONTACT';
export const SUCCESS_ADD_CONTACT = 'SUCCESS_ADD_CONTACT';
export const ERROR_ADD_CONTACT = 'ERROR_ADD_CONTACT';

export const LOADING_EDIT_CONTACT = 'LOADING_EDIT_CONTACT';
export const SUCCESS_EDIT_CONTACT = 'SUCCESS_EDIT_CONTACT';
export const ERROR_EDIT_CONTACT = 'ERROR_EDIT_CONTACT';

export const LOADING_DELETE_CONTACT = 'LOADING_DELETE_CONTACT';
export const SUCCESS_DELETE_CONTACT = 'SUCCESS_DELETE_CONTACT';
export const ERROR_DELETE_CONTACT = 'ERROR_DELETE_CONTACT';
